#配置文件环境配置
spring:
  profiles:
    active:
    - dev
    
---
spring:
  profiles: dev
  application:
    name:springcloud-config-lzj-dev
  
---
spring:
  profiles: prod
  application:
    name:springcloud-config-lzj-prod
  
---
spring:
  profiles: test
  application:
    name:springcloud-config-lzj-test

