#配置文件环境配置
    
---
server:
  port: 8021
spring:
  profiles: dev
    name:springcloud-config-client-lzj-dev
eureka: 
  client: 
    service-url: 
      defaultZone:org.lzj.springcloud-dev/eureka/  
---
spring:
  profiles: test
    name:springcloud-config-client-lzj-test

