#配置文件环境配置
spring:
  profiles:
    active: dev
    
---
server:
  port: 8021
spring:
  profiles: dev
    name:springcloud-config-client-lzj-dev
eureka: 
  client: 
    service-url: 
      defaultZone:org.lzj.springcloud-dev/eureka/  
  
---
server:
  port: 8022
spring:
  profiles: prod
    name:springcloud-config-client-lzj-prod
eureka: 
  client: 
    service-url: 
      defaultZone:org.lzj.springcloud-prod/eureka/   
---
server:
  port: 8023
spring:
  profiles: test
    name:springcloud-config-client-lzj-test
eureka: 
  client: 
    service-url: 
      defaultZone:org.lzj.springcloud-test/eureka/ 
